name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
jobs:
  deploy:
      # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
      
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
      
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20.12.2

    - name: Install dependencies
      run: npm install --force

    - name: Pre-build for production
      run: npm run predeploy
      
    - name: Deploy to GitHub Pages
      run: |
        npm install -g angular-cli-ghpages
        ngh --dir=dist/roxanne --no-silent
