name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20.12.2

    - name: Install dependencies
      run: npm install --force

    - name: Pre-build for production
      run: npm run predeploy

    - name: Build for production
      run: npm run deploy

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/roxanne 
        publish_branch: gh-pages
